#!/usr/bin/env python3
"""Keep the website walkthrough's NPC quotes in step with the patch.

    wtquotes.py norm FILE IDX      print string IDX of FILE as a quote must match it
    wtquotes.py check              check every quote in docs/walkthrough-npcs.json
    wtquotes.py ledger             rewrite docs/walkthrough-quotes.md from the JSON

The walkthrough on Bartok's Trading Post (bartoks-trading-post, /dimguil/walkthrough/)
quotes the patch's English. docs/walkthrough-npcs.json records, chapter by chapter, who
appears, a short blurb, and each quote with the file and string it came from. When a
quoted string's translation changes, `check` lists the quote, the chapter it sits in,
and what the string says now, so the site can be updated to match.

FILE is NPC_MES1-5, EVENTMES or SISETU. A quote must appear word for word in the
normalized string: speaker line and page breaks dropped, lines joined with spaces, the
opening " dropped, {ff12} (a character's name) as [name], {ff11}0 (a number) as
[number], and colour codes removed.
"""
import json, os, re, sys

ROOT = os.path.join(os.path.dirname(__file__), '..')
DATA = os.path.join(ROOT, 'docs', 'walkthrough-npcs.json')
LEDGER = os.path.join(ROOT, 'docs', 'walkthrough-quotes.md')
FILES = {**{f'NPC_MES{n}': f'NPC_MES{n}.OBJ.json' for n in range(1, 6)},
         'EVENTMES': 'EVENTMES.BIN.json', 'SISETU': 'SISETU.OBJ.json'}
_cache = {}


def strings(name):
    if name not in _cache:
        text = open(os.path.join(ROOT, 'translations', FILES[name]), encoding='utf-8').read()
        text = re.sub(r'//[^\n"]*\n', '\n', text)  # a few files carry // notes
        _cache[name] = json.loads(text)['sections'][0]['strings']
    return _cache[name]


def norm(name, idx):
    t = strings(name)[idx].get('translation') or ''
    t = t.replace('{ff12}', '[name]').replace('{ff11}0', '[number]')
    t = re.sub(r'\{ancient_(\w)\}', lambda m: m.group(1).upper(), t)
    t = re.sub(r'\{ff[0-9a-f]{2}\}[0-9]?', lambda m: '\n' if m.group(0) == '{ff26}' else '', t)
    t = t.replace('\r', '\n')
    lines = [l.strip() for l in t.split('\n')]
    if name.startswith('NPC_MES') and len(lines) > 1 and lines[1].startswith('"'):
        lines = lines[1:]  # the speaker's name heads the box
    text = ' '.join(l for l in lines if l)
    text = re.sub(r'^"', '', text)
    text = re.sub(r'[\]\[]', '', text) if name == 'EVENTMES' else text
    return re.sub(r'\s+', ' ', text).strip()


def quotes(data):
    for ch in data['chapters']:
        for who in ch.get('npcs', []):
            for q in who.get('quotes', []):
                yield ch, who, q


def check():
    data = json.load(open(DATA, encoding='utf-8'))
    bad = 0
    n = 0
    for ch, who, q in quotes(data):
        n += 1
        now = norm(q['file'], q['idx'])
        if q['text'] not in now:
            bad += 1
            print(f"!! chapter {ch['no']} ({ch['slug']}), {who['who']}: {q['file']} {q['idx']}")
            print(f"   quoted: {q['text']}")
            print(f"   now:    {now}\n")
    print(f'{n} quotes, {bad} changed' + ('' if bad else ', all match the patch'))
    return bad


def ledger():
    data = json.load(open(DATA, encoding='utf-8'))
    out = ['# Walkthrough quotes', '',
           'Generated by `scripts/wtquotes.py ledger` from `docs/walkthrough-npcs.json`; edit the JSON,',
           'not this file. Every patch line the website walkthrough quotes, by chapter. After changing a',
           'quoted string, run `scripts/wtquotes.py check`: it lists each quote that no longer matches,',
           'with the chapter and the string\'s new wording, to carry over to the site.', '']
    for ch in data['chapters']:
        qs = [(who, q) for who in ch.get('npcs', []) for q in who.get('quotes', [])]
        if not qs:
            continue
        out.append(f"## {ch['no']}. {ch['title']}")
        out.append('')
        out.append('| Who | String | Quote |')
        out.append('|---|---|---|')
        for who, q in qs:
            text = q['text'].replace('|', '\\|')
            out.append(f"| {q.get('speaker', who['who'])} | {q['file']} {q['idx']} | {text} |")
        out.append('')
    open(LEDGER, 'w', encoding='utf-8').write('\n'.join(out))
    print(f'wrote {os.path.relpath(LEDGER, ROOT)}')


def main():
    a = sys.argv[1:]
    if a[:1] == ['norm'] and len(a) == 3:
        print(norm(a[1], int(a[2])))
    elif a == ['check']:
        sys.exit(1 if check() else 0)
    elif a == ['ledger']:
        ledger()
    else:
        print(__doc__)
        sys.exit(2)


if __name__ == '__main__':
    main()
